version: '3'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=algo.*,apoc.*
    volumes:
      - '$PWD/data/:/data'
      - '$PWD/plugins:/plugins'
    ports:
      - '7474:7474'
      - '7687:7687'
  recommender:
    image: python
    volumes:
      - '$PWD/recommender:/app'
    ports:
      - '5000:5000'
    links:
      - neo4j:neo4j
    depends_on:
      - neo4j
    command: bash -c 'pip install py2neo pandas Flask flask-bootstrap && python /app/app.py'
#  jupyter:
#    image: jupyter/scipy-notebook
#    volumes:
#      - '$PWD/notebooks:/home/jovyan'
#    ports:
#      - '8888:8888'
#    links:
#      - neo4j:neo4j

